import type { TrichronoConfig } from '../types/index.js';

export const DEFAULT_CONFIG: Readonly<TrichronoConfig> = Object.freeze({
  colors: Object.freeze({
    background: '#0b0b12',
    overlay: '#111120',
    frame: '#222230',
    hours: '#ff3366',
    minutes: '#00d4ff',
    seconds: '#b8ff00',
    inactive: '#444455',
    text: '#e0e0e8',
  }),
  geometry: Object.freeze({
    sizeRatio: 0.42,
    botY: 0.58,
    halfBase: 0.95,
  }),
  frameLines: Object.freeze({
    width: 1.5,
    alpha: 0.3,
  }),
  hsl: Object.freeze({
    hueSource: 'seconds' as const,
    satSource: 'minutes' as const,
    litSource: 'hours' as const,
    satBase: 80,
    satRange: 20,
    litBase: 45,
    litAmplitude: 25,
    brightSat: 100,
    brightLitBoost: 30,
    brightLitMax: 90,
  }),
  scales: Object.freeze({
    majorTickRatio: 0.035,
    minorTickRatio: 0.018,
    majorWidth: 2.5,
    minorWidth: 1,
    activeAlpha: 0.9,
    inactiveAlpha: 0.2,
    labelOffsetPx: 16,
    labelSizeRatio: 0.04,
    labelActiveAlpha: 0.7,
    labelInactiveAlpha: 0.25,
    labelSizeMin: 10,
    labelFontFamily: "'Helvetica Neue', Arial, sans-serif",
    tickNormalOffset: 2,
    hoursDivisions: 24,
    minutesDivisions: 60,
    secondsDivisions: 60,
    hoursMajorEvery: 6,
    minutesMajorEvery: 15,
    secondsMajorEvery: 15,
  }),
  edgeProgress: Object.freeze({
    passes: Object.freeze([
      Object.freeze({
        width: 6,
        alpha: 1.0,
        stops: Object.freeze([
          Object.freeze({ position: 0, alphaHex: '00' }),
          Object.freeze({ position: 0.7, alphaHex: '44' }),
          Object.freeze({ position: 1, alphaHex: 'aa' }),
        ]),
      }),
    ]),
    coreWidth: 3,
    coreAlpha: 0.9,
    coreTailLength: 0.03,
  }),
  triangles: Object.freeze({
    sectorLayers: Object.freeze([
      Object.freeze({ visible: false, hueOffset: 180, lightnessMultiplier: 0.85, fillAlpha: 0.2, borderAlpha: 0.45 }),
    ]),
    crossLayers: Object.freeze([
      Object.freeze({ visible: false, hueOffset: 60, lightnessMultiplier: 0.95, fillAlpha: 0.3, borderAlpha: 0.55 }),
    ]),
    wedgeLayers: Object.freeze([
      Object.freeze({ visible: false, hueOffset: 90, lightnessMultiplier: 1.0, fillAlpha: 0.35, borderAlpha: 0.65 }),
    ]),
    gapLayers: Object.freeze([
      Object.freeze({ visible: false, hueOffset: 0, lightnessMultiplier: 0.7, fillAlpha: 0.15, borderAlpha: 0.3 }),
    ]),
    primaryLayer: Object.freeze({
      visible: true,
      hueOffset: 0,
      lightnessMultiplier: 1.1,
      fillAlpha: 0.85,
      borderAlpha: 0.9,
    }),
    glowPasses: Object.freeze([
      Object.freeze({ width: 16, alphaMultiplier: 0.08 }),
      Object.freeze({ width: 10, alphaMultiplier: 0.15 }),
      Object.freeze({ width: 6, alphaMultiplier: 0.30 }),
      Object.freeze({ width: 3, alphaMultiplier: 0.60 }),
      Object.freeze({ width: 1.5, alphaMultiplier: 1.00 }),
    ]),
    shadowBlur: 50,
    shadowAlpha: 0.5,
    compositeOp: 'source-over' as GlobalCompositeOperation,
    hueStep: 60,
    lighterHueOffset: 30,
    lighterLitBoost: 10,
    darkerHueOffset: 30,
    darkerLitReduction: 5,
    gradientRadiusRatio: 0.5,
    lightGradientAlpha: 0.25,
    darkGradientAlpha: 0.2,
    borderLineWidth: 2.5,
    shadowLineWidth: 2,
    plasma: Object.freeze({
      enabled: true,
      alpha: 0.55,
      speed: 0.8,
      textureSize: 512,
      blendMode: 'source-over' as GlobalCompositeOperation,
    }),
  }),
  tips: Object.freeze({
    hours: Object.freeze({ radius: 6, glowRadiusRatio: 0.08 }),
    minutes: Object.freeze({ radius: 5, glowRadiusRatio: 0.07 }),
    seconds: Object.freeze({ radius: 4, glowRadiusRatio: 0.06 }),
    vertexRadius: 4,
    vertexAlpha: 0.6,
    innerRadiusRatio: 0.5,
    innerAlpha: 0.7,
    innerColor: '#ffffff',
    gradientStops: Object.freeze([
      Object.freeze({ position: 0, alphaHex: 'ff' }),
      Object.freeze({ position: 0.3, alphaHex: '88' }),
      Object.freeze({ position: 1, alphaHex: '00' }),
    ]),
  }),
  edgeLabels: Object.freeze({
    visible: false,
    alpha: 0.35,
    offsetRatio: 0.12,
    fontSizeRatio: 0.038,
    fontSizeMin: 10,
    fontWeight: 300,
    fontFamily: "'Helvetica Neue', Arial, sans-serif",
  }),
  digitalTime: Object.freeze({
    xOffsetRatio: 0,
    yOffsetRatio: 0.82,
    fontSizeRatio: 0.06,
    fontSizeMin: 14,
    fontFamily: "Georgia, 'Times New Roman', serif",
    fontWeight: 700,
    alpha: 0.25,
    visible: true,
    showSeconds: false,
    color: '#e0e0e8',
    shadowBlur: 0,
    shadowColor: '#000000',
  }),
  background: Object.freeze({
    overlayRadiusRatio: 1.5,
  }),
  edgeMapping: Object.freeze({
    AB: 'hours',
    BC: 'minutes',
    CA: 'seconds',
  }),
} as const);
